### ISSUE TITLE
Not Redacting

### ISSUE THREAD

**Issue by rhino1977** [archetyped/eyes-only#2]
I installed Version: 1.0.8, and I am using WordPress 4.8.1  .. plugin installed successfully, I have the WYSIWG option to redact sections of text.  Though when I preview/publish, it shows the complete text.

The URL I published, http://ryan.brinkworth.id.au/2017/08/redact-test/
I redacted all but the first and last sentences of the body.

I have a few plugins installed.

**Comment by archetyped** [comment]
Hi, apologies for the delayed response.  The link you provided does not appear to be active.  Please provide an updated link and I would be glad to take another look.

Also note that redaction is designed to occur for **visitors** to the site only.  Authorized users (i.e. logged in users) will see the original unredacted content.  If you are logged in and want to see the redacted version of a post, you'll need to log out or open a private window to view the post as a visitor.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
